### ISSUE TITLE
Why add JSDOM if it comes with Jest?

### ISSUE THREAD

**Issue by kon-rad** [the-road-to-learn-react/react-testing-mocha-chai-enzyme#22]
Hello,
Why did you set up jsdom this way as in this file: react-components-test-setup/test/dom.js
Doesn't jsdom come with jest alrady when run with--env=jsdom option?

Label: Question

**Comment by rwieruch** [comment]
I don't know. Does it? Did you try without it? :)

**Comment by kon-rad** [comment]
yes I believe so. I haven't found much documentation on this from jest, but found it referenced in various s/o posts like this one https://stackoverflow.com/questions/40970780/how-to-setup-jsdom-when-working-with-jest

**Comment by rwieruch** [comment]
Ah okay. Then, if using Jest, I guess you don't need it. I just added it because I started with Enzyme in this tutorial https://www.robinwieruch.de/react-testing-tutorial and transitioned over to Jest. I think you need it for Enzyme though if not using it with Jest.
